$(function(){
    $("#hide").click(function(){
        $('#cheak').hide(1000)
    })

    $("#show").click(function(){
        $('#cheak').show(2000)
    })
    $("#toggle").click(function(){
        $('#cheak').toggle(2000)
    })
    $("#fadein").click(function(){
        $('#fade').fadeIn(2000)
    })
    $("#fadeout").click(function(){
        $('#fade').fadeOut(2000)
    })
    $("#fadetoggle").click(function(){
        $('#fade').fadeToggle(2000)
    })
    $("#fadeto").click(function(){
        $('#fade').fadeTo(2000,0.5)
    })
    $(".fadetoggle").click(function(){
        $('.fade').fadeToggle(5000)
    })
})
